### ISSUE TITLE
Absdef

### ISSUE THREAD

**Issue by HamzaAxiom** [AmeerHamza0220/TicTacToe#1]

**Comment by AmeerHamza0220** [comment]
![screenshot_2017-10-06-15-04-16](https://user-images.githubusercontent.com/31588843/31273353-a9f6edb8-aaa7-11e7-929a-cf96de9e4bdf.png)

**Comment by AmeerHamza0220** [comment]
![screenshot](https://user-images.githubusercontent.com/31588843/31273387-d70da486-aaa7-11e7-95cb-8e55d0d45dd8.png)
